export const FETCH_VEGGIES_REQUEST = "FETCH_VEGGIES_REQUEST";
export const FETCH_VEGGIES_SUCCESS = "FETCH_VEGGIES_SUCCESS";
export const FETCH_VEGGIES_FAILURE = "FETCH_VEGGIES_FAILURE";
export const UPDATE_STOCK_QUANTITY = "UPDATE_STOCK_QUANTITY";
